set nocompatible
set ignorecase " enable smartcase search sensitivity "
set smartcase
set autoread
set history=500
set wildmenu
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set hlsearch " enable highlight search pattern "
set noerrorbells
set novisualbell
set background=dark
set number
set relativenumber

set showmatch " show the matching part of pairs [] {} and () "

set ruler
syntax on
set showcmd
set mouse=a
set nowrap

colo koehler

set tabstop	    =4
set softtabstop	=4
set shiftwidth	=4
set textwidth	=79
set expandtab

nnoremap <C-Up> 5k
nnoremap <C-Down> 5j

nnoremap <C-K> 5k
nnoremap <C-J> 5j

vmap <C-y> :w! ~/.vimbuffer<CR>
nmap <C-y> :.w! ~/.vimbuffer<CR>
map <C-p> :r ~/.vimbuffer<CR>
map <C-n> :set number! relativenumber!<CR>

set timeoutlen=1000 ttimeoutlen=0
